version: '3'

services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: datapool
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_ROOT_PASSWORD: postgres
      TZ: 'Asia/Tokyo'
    volumes:
    - ./docker/db/db:/var/lib/postgres/data
    - ./docker/db/data:/var/lib/postgres
    - ./docker/db/my.cnf:/etc/postgres/conf.d/my.cnf
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 5432:5432